#!/bin/sh
#/etc/init.d/argus_watchdog: start watchdog daemon.

### BEGIN INIT INFO
# Provides:          argus_watchdog
# Short-Description: Start software argus_watchdog daemon
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

NAME=argus_watchdog
DAEMON=/etc/argus_watchdog/argus_watchdog
CONFIG=/etc/argus_watchdog/argus_watchdog.conf

test -x $DAEMON || exit 0
test -f $CONFIG || exit 0

options="--no-action --force --config-file=$CONFIG"

STOP_RETRY_SCHEDULE='TERM/5/KILL/1'

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
	log_begin_msg "Starting $NAME daemon..."
	start-stop-daemon --start --quiet --exec $DAEMON -- $options
	log_end_msg $?
    ;;

  stop)
	log_begin_msg "Stopping $NAME daemon..."
	start-stop-daemon --stop --quiet --exec $DAEMON --retry $STOP_RETRY_SCHEDULE
	log_end_msg $?
    ;;

  restart)
    $0 force-reload
    ;;

  force-reload)
  	$0 stop
  	$0 start
    ;;

  status)
    status_of_proc "$DAEMON" "$NAME"
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1

esac

exit 0
